
public class addInstruction {
	public static void main(String[] args) {
		String kitchenInstCn = "台面一般用湿布清洁即可，如果有长期积累的油污斑点可用肥皂水及中性清洁剂清洗，以画圆方式由外及里轻轻擦拭，切忌使用化学性强的清洁剂。尤其是石材台面一定要避免化学性强的清洁剂接触台面。用湿布清洁台面后，再用干抹布或者报纸吸干。在做饭时，避免将热锅、热水壶直接放到台面，从而损伤台面，甚至导致台面开裂。假期期间，如果要频繁使用厨房，不妨在灶台上铺上一层厚一点的纸，然后按时更换干净的保洁纸，这样可以减少灶台污染。煤气灶是厨房内最容易弄脏的地方，一般做完饭后煤气灶则是“惨不忍睹”，为了便于清洁煤气灶，做完饭后，应在煤气灶还有余温时用湿布加肥皂水或苏打水擦拭，如果待煤气灶完全冷却后再擦拭，油污、煮粥溅出的米汤等就很难擦净。";
		String kitchenInstEn = "Usually with a damp cloth to clean the table , if there is long-term accumulation of grease spots soapy water and a mild detergent , to draw a circle way gently wipe from the outside and inside , avoid the use of strong chemical cleaners . Especially stone countertops must be avoided strong chemical cleaning agent contact mesa . After using a damp cloth to clean the countertop with a dry cloth or paper dry .When cooking, avoid hot pan , kettle directly into the table, which damage the countertops, countertops and even lead to cracking. During the holidays , if you frequently use the kitchen stove may wish to spread on a thick bond paper , and then replace the clean time cleaning paper , thus reducing pollution stove .Gas stove in the kitchen is the easiest dirty place , generally done after a meal gas stove is appalling , in order to facilitate the cleaning gas stove , finished dinner, should be used when there is gas stove sweltering wet or soapy water Bucharest soda water to clean , if gas stove until completely cool before cleaning, oil, rice porridge spilled and so it is difficult to wipe.";
		String kitchenInstDe = "Normalerweise mit einem feuchten Tuch, um den Tisch zu reinigen , wenn es langfristige   Akkumulation von Fettflecken Seifenwasser  und einem milden Reinigungsmittel ist , um einen Kreis zu zeichnen Art und Weise sanft von außen wischen und nach innen, vermeiden den Einsatz von starken chemischen Reiniger. Besonders Steincountertops müssen starke chemische Reinigungsmittel Kontakt Mesa vermieden werden. Nach einem feuchten Tuch mit der Arbeitsplatte mit einem trockenen Tuch oder Papier trocken zu reinigen.Beim Kochen , vermeiden heiße Pfanne , Kessel direkt in die Tabelle , die die Arbeitsplatten , Arbeitsplatten beschädigen und führen sogar zu knacken. Während der Ferien , wenn Sie häufig die Küchenherd verwenden kann auf einem dicken Bondpapier zu verbreiten wollen , und dann tauschen Sie die Reinigungszeit Reinigungspapier und eine Verschmutzung Ofen zu reduzieren.Gasherd in der Küche ist die einfachste schmutzigen Ort , in der Regel durchgeführt , nachdem eine Mahlzeit Gasherd ist entsetzlich  , um die Reinigungsgasherd , fertige Abendessen zu erleichtern, sollten verwendet werden, wenn Gasherd nass oder Seifenwasser Bukarest brütender Sodawasser zu reinigen , wenn Gasherd , bis sie vollständig abgekühlt ist, bevor Reinigung , Öl, Reis Brei verschüttet und so ist es schwierig zu wischen.";
	
		String kitchenInstCn1= "橱柜的水池既要洗菜还要洗碗，容易沾染洗碗水中的油垢，如果平时没有完全洗净，过一段时间后水池壁则会沾上一层油污。尤其是长假期间厨房使用频繁，更容易积累脏物，如果没有专门的水池清洁剂，在有油污的地方撒一点盐，然后用废旧的保鲜膜上下擦拭，擦拭后用温水冲洗几遍，也能让水池光亮如新。水池的四周弯角和下水处可以准备专门的小刷子或者牙刷用细盐、肥皂水、清洁剂擦拭，下水处的水盖也最好用温肥皂水浸泡20-30分钟，达到理想的去污效果。水龙头的污垢也不应忽视，对付陈年的污垢可以用钢丝球抹上清洁剂进行擦拭，用清水清洁后，再用湿抹布蘸上牙膏或者直接用柠檬片反复擦拭，能让水龙头恢复光亮。　　";
		String kitchenInstEn1="Cabinet basin is necessary to wash the dishes but also vegetables , easily contaminated with grease dishwashing water , usually if not completely washed over a period of time after the pool wall is coated with a layer of oil . Especially during the holiday kitchen use frequent and more likely to accumulate dirt , if there is no specific pool cleaner, there is oil in place a pinch of salt , then wipe up and down the waste of plastic wrap , wipe with warm water several times , but also let pond bright as new.Four weeks at the corners and the water tank can prepare a special small brush or a toothbrush with a thin salt , soap , detergent to clean the water covers the water at it's best with warm soapy water to soak for 20-30 minutes to achieve the desired decontamination effect.Faucet dirt should not be overlooked , can deal with the aging of the dirt with a steel ball cast detergent wipe with water after cleaning , then wet rag dipped in toothpaste or repeatedly wipe directly with lemon slices , let the faucet resume shine .";
		String kitchenInstDe1="Kabinett Becken ist notwendig, die Gerichte, aber auch Gemüse zu waschen , leicht mit Fett Spülwasser verunreinigt ist, wenn in der Regel nicht vollständig über einen bestimmten Zeitraum gewaschen , nachdem der Beckenwand mit einer Schicht aus Öl beschichtet ist. Vor allem während der Ferienküche nutzen häufiger und wahrscheinlich Schmutz ansammeln , wenn es keine spezifische Pool-Reiniger ist, gibt es Öl an Ort und Stelle eine Prise Salz , dann wischen oben und unten die Verschwendung von Plastikfolie , wischen Sie mit warmem Wasser mehrmals , aber auch lassen Teich hell wie neu.Vier Wochen an den Ecken und das Beckenwasser kann eine spezielle kleine Bürste vorbereiten oder eine Zahnbürste mit einem dünnen Salz, Seife, Waschmittel zu sauberem Wasser ist auch die beste Abdeckung am Wasser getränkt in warmem Seifenwasser für 20-30 Minuten die gewünschte Dekontamination zu erreichen Wirkung .Hahn Schmutz sollte nicht übersehen  werden , kann mit der Alterung der Schmutz befassen sich mit einer Stahlkugel gegossen Waschmittel mit Wasser abwischen nach der Reinigung , dann nassen Lappen eingetaucht  in Zahnpasta oder wiederholt wischen direkt mit Zitronenscheiben , lassen Sie den Wasserhahn wieder aufnehmen Glanz.";
	
		
	}
}
